New

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -9,14 +9,17 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: frontend
     strategy:
       matrix:
         node-version: [18.x]
+        # Set Node.js version, you can extend the matrix if you want to test multiple versions
 
     steps:
       # Checkout the repository
-      - name: Checkout code
-        uses: actions/checkout@v3
+      - uses: actions/checkout@v3
 
       # Set up Node.js environment
       - name: Set up Node.js ${{ matrix.node-version }}
@@ -24,29 +27,27 @@ jobs:
         with:
           node-version: ${{ matrix.node-version }}
           cache: 'npm'
-          cache-dependency-path: 'projectassistant/frontend/package-lock.json'
+          cache-dependency-path: '**/package-lock.json'
 
-      # Install dependencies in 'projectassistant/frontend'
+      # Install dependencies
       - name: Install dependencies
         run: npm ci
-        working-directory: projectassistant/frontend
 
-      # Build the project in 'projectassistant/frontend'
+      # Build the project
       - name: Build project
         run: NODE_OPTIONS=--max_old_space_size=8192 npm run build
-        working-directory: projectassistant/frontend
 
-      # Verify that the 'static' directory has been created successfully
+      # Verify static directory is created successfully
       - name: Verify static directory
-        run: ls -al projectassistant/static || echo "Static directory not found!"
+        run: ls -al ../static || echo "Static directory not found!"
 
-      # Create a zip file for deployment from the 'static' folder
+      # Create zip for deployment
       - name: Create deployment zip
         run: |
-          cd projectassistant/static
-          zip -r ../../static.zip .
+          cd ../static
+          zip -r ../static.zip .
 
-      # Upload the deployment package as an artifact for later use
+      # Upload the deployment package as an artifact
       - name: Upload artifact for deployment jobs
         uses: actions/upload-artifact@v3
         with:
@@ -57,13 +58,13 @@ jobs:
     runs-on: ubuntu-latest
     needs: build
     environment:
-      name: 'Production'
+      name: 'dev'
       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
     permissions:
       id-token: write  # This is required for requesting the JWT
 
     steps:
-      # Download the artifact created in the build job
+      # Download the artifact from the build job
       - name: Download artifact from build job
         uses: actions/download-artifact@v3
         with:
@@ -71,7 +72,7 @@ jobs:
 
       # Unzip the downloaded artifact
       - name: Unzip artifact for deployment
-        run: unzip static.zip -d projectassistant/static
+        run: unzip static.zip
 
       # Login to Azure using Service Principal
       - name: Login to Azure using Service Principal
@@ -83,12 +84,11 @@ jobs:
       - name: Set Azure Subscription explicitly
         run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
-      # Deploy to Azure Web App with the 'clean' flag to ensure no conflicts
+      # Deploy to Azure Web App
       - name: Deploy to Azure Web App
         uses: azure/webapps-deploy@v2
         id: deploy-to-webapp
         with:
           app-name: 'project-assistant'
-          slot-name: 'dev'  # Set to 'dev' since you mentioned creating a dev environment
-          package: projectassistant/static
-          clean: true  # Clean the destination before deploying to avoid conflicts
+          slot-name: 'dev'
+          package: .
