Reset to baseline

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -35,13 +35,13 @@ jobs:
 
       # Debugging Step: Verify that static directory exists after the build
     - name: List Static Directory Contents
-      run: ls -al ../static || echo "Static directory not found!"
+      run: ls -al ./projectassistant/static || echo "Static directory not found!"
 
       # Deploy to Azure Web App
     - name: Deploy to Azure Web App
       if: github.ref == 'refs/heads/main'
       uses: azure/webapps-deploy@v2
       with:
-        app-name: 'project-assistant'  # Replace with your Azure App Service name
+        app-name: 'project-assistant'
         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
-        package: ../static
+        package: projectassistant/static
